# https://github.com/zod-org/zod-docs/actions

title: Zod
logo: /assets/images/logo.png

# https://shopify.github.io/liquid/
# https://jekyllrb.com/
# https://github.com/pmarsceill/just-the-docs
# https://pmarsceill.github.io/just-the-docs/
remote_theme: pmarsceill/just-the-docs # use for gh-pages
# theme: just-the-docs # use for local development

color_scheme: zod_color_scheme
search_enabled: true

permalink: pretty

# Back to top link
back_to_top: true
back_to_top_text: Back to top

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
# Aux links for the upper right navigation
aux_links:
    Discord:
        - https://discord.gg/hWsm94RcUQ
    GitHub:
        - https://github.com/colinhacks/zod
    npm:
        - https://www.npmjs.com/package/zod

# collections:
#     docs:
#         output: true
#         # permalink: :path
#         # permalink: :path/:basename

# defaults:
#     - scope:
#           path: docs/*
#       values:
#           layout: doc-page
#           #   permalink: :basename
#           #   permalink: :path
#           #   permalink: :path/../:basename
#           permalink: :path/../../../
#           #   permalink: :path/:basename

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: Edit this page on GitHub.
gh_edit_repository: https://github.com/zod-org/zod-docs # the github URL for your repo
gh_edit_branch: gh-pages # the branch that your docs is served from
gh_edit_view_mode: tree # "tree" or "edit" if you want the user to jump into the editor immediately
#
#
#
#
# plugins:
#
#
#
#
#
#
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#     Write an awesome description for your new site here. You can edit this
#     line in _config.yml. It will appear in your document head meta (for
#     Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: jekyll
# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
